if(CMAKE_SYSTEM_NAME MATCHES "Windows")
    set(LW_CMAKE_WINDOWS TRUE)
    add_definitions(-DLW_CMAKE_WINDOWS)
elseif(CMAKE_SYSTEM_NAME MATCHES "Linux")
    set(LW_CMAKE_LINUX TRUE)
    add_definitions(-DLW_CMAKE_LINUX)
else()
    message(FATAL_ERROR "Cannot identify OS")
endif(CMAKE_SYSTEM_NAME MATCHES "Windows")
